"""add column post_type in newsletter table 

Revision ID: 37a8e5d3d79f
Revises: 
Create Date: 2025-08-11 12:13:59.246079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a8e5d3d79f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.drop_column('post_type')

    # ### end Alembic commands ###
